### ISSUE TITLE
gpsFromImage returning nan

### ISSUE THREAD

**Issue by GregProbst** [rgerum/cameratransform#14]
Thanks for your hard work on this library and the great documentation. We have been experimenting with the gpsFromImage function trying to get real world GPS coords from a point in the image. We have run into an issue where some points in the image are returning "nan" and we are not sure what is causing that.

Here is an example:
```
import cameratransform.camera as ct
from cameratransform.lens_distortion import BrownLensDistortion

projection = ct.RectilinearProjection(image=(1280, 720),
                                      focallength_x_px=722.7379,
                                      focallength_y_px=726.1398,
                                      center_x_px=663.8862,
                                      center_y_px=335.0579,
                                      sensor_width_mm=4.96,
                                      sensor_height_mm=3.72)
orientation = ct.SpatialOrientation(elevation_m=2.0,
                                    tilt_deg=90.0,
                                    roll_deg=0.0,
                                    heading_deg=358.950422)
distortion = BrownLensDistortion(k1=-0.3581,
                                 k2=0.1039,
                                 projection=projection)

cam = ct.Camera(projection, orientation, distortion)

cam.setGPSpos(lat=40.55660, lon=-111.89720)
coords = cam.gpsFromImage([[288.0, 228.0]])
print(coords)
```
the results of this print:
```
[array(array([nan]), dtype=object) array(array([nan]), dtype=object)
 array([nan])]
```

We have successfully used the library for other points. Is this expected behavior and we are just using the library incorrectly? Any help you could provide would be appreciated.

Thanks,
Greg

**Comment by rgerum** [comment]
in this example the camera is pointing to the horizon (tilt = 90deg) therefore, the ray from this image point does not reach the ground plane but shows sky.

**Comment by GregProbst** [comment]
Does that mean anything above the horizon is invalid? I could not identify the GPS location of say a billboard from a car?

**Comment by rgerum** [comment]
When you try to project back from the camera to the 3D space, the projection is not a unique mapping, because the image is 2D and the depth information is lost. Therefore, if you want to project from the 2D image to the 3D space, you need one additional contraint, e.g. the height of the object. Per default cameratransform projects to the 3D xy plane, i.e. the floor or ground. But you could specify any height. If you have a point over the horizon, there does not exist any point on the ground that corresponds to this pixel. Hence, "nan" is returned.
